#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# userID1 - First User
# userID2 - Second User

declare -a lids=(userID1 userID2)

found=false
current_user=$(whoami)

# Redirect output to stderr.
exec 1>&2


#echo ${lids[1]}

for i in "${lids[@]}"
do
	if [ "$i" == $current_user ] ; then
		found=true
		break
	fi
done

echo $found

# Cross platform projects tend to avoid non-ascii filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if [ $found != "true" ]
then
	echo "Error: You do not have access to push to this repository."
	echo
	echo "Please contact the XXXX mail group to push changes"
	echo
	exit 1
fi
